### ISSUE TITLE
Update to public package

### ISSUE THREAD

**Issue by franz-josef-kaiser** [clarkmcc/go-hubspot#9]
First off: It's a very nice project. Thanks for providing it to others!

From the Hubspot API documentation, I saw (in comparison to what was archived around your commit last year via wayback machine/ internet archive) that there were quite some changes.

I tried to build a new set to add a PR to this repo, but I am not sure I understand your process completely. You seem to have various versions in the `./generated` folder. What would be the target/ output dir for the next update? Here you can see the local Docker container with a volume mapping where `<WHAT-FOLDER-NAME-HERE?>` is the part that's not clear to me.

```
docker run --rm -v "${PWD}/generated/<WHAT-FOLDER-NAME-HERE?>:/local" openapitools/openapi-generator-cli generate \
    -i https://raw.githubusercontent.com/openapitools/openapi-generator/master/modules/openapi-generator/src/test/resources/3_0/petstore.yaml \
    -g go \
    -o /local/out/go
```

If you can replicate the generation with the container above, I will add a README-extension with the PR as well.

Just a suggestion: Maybe the generation could be auto generated using GitHub actions using above image?

**Comment by clarkmcc** [comment]
Hi! Love the idea of generation in a container, that will make it more friendly and approachable to use. Currently you can generate everything (directories, formatting, patching, etc) with

    go generate ./...

This handles a lot of stuff that isn't handled natively by the openapi-generator. You can see everything we're doing manually on top of generation [here](https://github.com/clarkmcc/go-hubspot/blob/master/cmd/generate/main.go).

The main challenge with automated the generation is that manual patches need to be verified by hand and tested before committing. For example, I just updated this library to the newest version of the Hubspot client API spec and the recent auth changes broke how we're doing auth in this library, so I had to [resolve that first](https://github.com/clarkmcc/go-hubspot/pull/10/commits/927bfcae3dc4851e70f40ff1ce1f4ee2623bd9fa).

Once/if API generation is a stable hands-off process, then I think we can automate it. Until then, it seems like manual generation with `go generate` + manual auditing might be required.

Thoughts?

**Comment by franz-josef-kaiser** [comment]
Well, it's my third day with Go (decade+ of other languages so far), so please take this into account when weighting my suggestions.

For the process itself, I'd say it's quite safe to automate towards a PR as this forces (haha) _someone_ to do a review before merging.

I read through the `generator` file and saw that the process currently is [bound to your user](https://github.com/clarkmcc/go-hubspot/blob/20c2f9cbf93655fa7201167e6acfac346b0467c4/cmd/generate/main.go#L574) anyway. I also found that you execute the [`generator` call](https://github.com/clarkmcc/go-hubspot/blob/20c2f9cbf93655fa7201167e6acfac346b0467c4/cmd/generate/main.go#L614-L621) in the process. Maybe it's a first step to move this to Docker so the at least the environment is stable (therefore more reliable and comparable) between runs and independent from a local machines setup?

One more thing -I know I am going off route here- is the general quality of the generated READMEs. As someone not that used to Go, I am having a hard time interpreting the examples. I couldn't get around querying the search API with a POST request and adding `FilterGroups`. The generated docs are pointing to parts that are not available in the repo itself (like the `openapisomething` package) and are generally quite confusing. I managed to build a quick request using `http.Client` tough, while I completely failed to do something quite simple by reading the docs and trying to replicate what I found there. Anyways, that might be just me.

**Comment by clarkmcc** [comment]
Congrats! Welcome to Go.

If you want to propose an automated process for generating clients, I'd be happy to look at it. I'm not sure that I totally understand the proposal, initially I was thinking the idea was Github actions would run periodically and open PRs against the repo, but in your latest message it sounds like you're thinking more along the lines of generation in a docker container so that you don't have to install any tooling in your environment. I'm happy to consider either, the Github Actions approach definitely sounds more involved (periodic generation, automatic PRs, etc).

So the env variables that you mentioned are required by openapi generator in order to construct proper Go imports. The way it works is like this

```go
import "github.com/$GIT_USER_ID/$GIT_REPO_ID"
```

so really the variables just need to match the name of the repo hosting the code rather then being specific to me or someone else. In other words, even if you're running this on your machine to prepare a PR for this repo, you'd still need my  username and repo name in there in order to produce the proper code generation from openapi generator.

Totally agree on the generated readmes. To be honest, openapi-generator is absolute garbage at code generation. I've considered switching to https://github.com/deepmap/oapi-codegen since it's much more tailored to the Go language, but that's a breaking change for this library so I've put it on the back burner. This isn't a whole lot of help to you since you're just getting started in Go, but after some time in Go generally, the usage for this library should become more intuitive without referring to the readmes. I use Goland, and the intellisense is really all I'm using to figure out what I need to do. If you'd like, tell me what you're trying to do and I'd be happy to prepare a few code examples using this library to get you up and going.

**Comment by franz-josef-kaiser** [comment]
Hey @clarkmcc ! Thanks for the quick update.

**Comment by clarkmcc** [comment]
@franz-josef-kaiser sorry, this issue auto-closed when I merged the PR. I'd say feel free to create issues for the other ideas/feedback you have and I'll prioritize them accordingly!
